version: '3'
services:
  nginx:
    image: gscool/nginx
    environment:
     - PORT=443
    depends_on:
      - web
    ports:
     - "443:443"
    links:
      - web:web
  web:
    image: gscool/blog
    ports:
     - "7001:7001"
    environment:
     - PORT=7001
